import { Pack, Source, DiagnosticsData } from '../types';
import { generateLocalEmbedding } from '../search/vector-search';

export const INITIAL_SOURCES: Source[] = [
  {
    id: '411',
    name: '411 Scenepacks',
    baseUrl: 'https://scenepacks.com',
    badgeName: '411 Scenepacks',
    badgeColor: 'bg-blue-500/15 text-blue-400 border border-blue-500/30',
    enabled: true,
    lastCrawledAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    packCount: 5820,
  },
  {
    id: 'veel',
    name: 'Veel Scenepacks',
    baseUrl: 'https://veelscp.com',
    badgeName: 'Veel SCP',
    badgeColor: 'bg-pink-500/15 text-pink-400 border border-pink-500/30',
    enabled: true,
    lastCrawledAt: new Date(Date.now() - 3600000 * 1).toISOString(),
    packCount: 3150,
  },
  {
    id: 'editpacks',
    name: 'EditPacks',
    baseUrl: 'https://editpacks.org',
    badgeName: 'EditPacks',
    badgeColor: 'bg-emerald-500/15 text-emerald-400 border border-emerald-500/30',
    enabled: true,
    lastCrawledAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    packCount: 1680,
  },
  {
    id: 'suits',
    name: 'SuitsTM Scenepacks',
    baseUrl: 'https://suitstmscenepacks.com',
    badgeName: 'Suits™',
    badgeColor: 'bg-amber-500/15 text-amber-400 border border-amber-500/30',
    enabled: true,
    lastCrawledAt: new Date(Date.now() - 3600000 * 3).toISOString(),
    packCount: 140,
  },
];

const RAW_PACKS_DATA: Omit<Pack, 'embedding'>[] = [
  // CRUELLA (2021) - Multiple packs from 411 and Veel
  {
    id: '411_cruella_estella_1080p',
    sourceId: '411',
    externalId: 'cruella-estella-1080p',
    title: 'Cruella (2021) - Estella Scenepack',
    mediaTitle: 'Cruella',
    mediaType: 'movie',
    year: 2021,
    characterName: 'Estella',
    actorName: 'Emma Stone',
    directorName: 'Craig Gillespie',
    creatorName: '411 Archive',
    category: 'Movie Scenepacks',
    quality: '1080p',
    codec: 'H.264',
    description: 'Estella transformation scenes, discovering Baroness killed her mother at the cliff, grief at fountain, revenge fashion entrance, red dress fire scene.',
    sourceUrl: 'https://scenepacks.com/pack/cruella-2021-estella',
    downloadPageUrl: 'https://scenepacks.com/download/cruella-estella-1080p',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/rTh4K5uw9HypmpGslcKd4QfHl93.jpg',
    popularity: 98,
    downloadCount: 4320,
    publishedAt: '2023-01-15T12:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['cruella', 'estella', 'emma stone', 'mother death reveal', 'revenge', 'badass entrance', 'grief', 'betrayal', 'fashion'],
    vibeTags: ['grief', 'revenge', 'betrayal', 'badass', 'confident', 'party', 'sadness', 'murder discovery'],
  },
  {
    id: 'veel_cruella_2021_4k',
    sourceId: 'veel',
    externalId: 'cruella-2021-4k-hdr',
    title: 'Cruella (2021) - Cruella De Vil [4K HDR]',
    mediaTitle: 'Cruella',
    mediaType: 'movie',
    year: 2021,
    characterName: 'Cruella',
    actorName: 'Emma Stone',
    directorName: 'Craig Gillespie',
    creatorName: 'Veel SCP Master',
    category: '4K Cinema',
    quality: '4K',
    codec: 'H.265 (HEVC)',
    description: 'High bitrate 4K clips of Cruella revenge gala entrances, dumpster truck trash dress, finding out truth about mother, villain laugh.',
    sourceUrl: 'https://veelscp.com/pack/cruella-2021-4k',
    downloadPageUrl: 'https://veelscp.com/dl/cruella-2021-4k',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/rTh4K5uw9HypmpGslcKd4QfHl93.jpg',
    popularity: 96,
    downloadCount: 5120,
    publishedAt: '2023-02-10T14:30:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['cruella', 'emma stone', 'villain', 'badass', '4k', 'hevc', 'fashion', 'gala', 'revenge', 'mother murder reveal'],
    vibeTags: ['villain', 'badass', 'revenge', 'confidence', 'party', 'luxury', 'velocity'],
  },
  {
    id: '411_cruella_baroness',
    sourceId: '411',
    externalId: 'cruella-baroness-von-hellman',
    title: 'Cruella (2021) - Baroness von Hellman',
    mediaTitle: 'Cruella',
    mediaType: 'movie',
    year: 2021,
    characterName: 'Baroness von Hellman',
    actorName: 'Emma Thompson',
    directorName: 'Craig Gillespie',
    creatorName: '411 Team',
    category: 'Villain Scenepacks',
    quality: '1080p',
    codec: 'H.264',
    description: 'Baroness cruel scenes, narcissist boss energy, dog whistle cliff scene, arrogant smiles, cold betrayal scenes.',
    sourceUrl: 'https://scenepacks.com/pack/cruella-baroness',
    downloadPageUrl: 'https://scenepacks.com/download/cruella-baroness',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/rTh4K5uw9HypmpGslcKd4QfHl93.jpg',
    popularity: 82,
    downloadCount: 1840,
    publishedAt: '2023-03-01T09:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['cruella', 'baroness', 'emma thompson', 'villain', 'narcissist', 'luxury', 'betrayal'],
    vibeTags: ['villain', 'confident', 'betrayal', 'party', 'badass'],
  },

  // THE BATMAN (2022)
  {
    id: '411_the_batman_bruce_wayne',
    sourceId: '411',
    externalId: 'the-batman-2022-bruce-wayne',
    title: 'The Batman (2022) - Bruce Wayne & Batman',
    mediaTitle: 'The Batman',
    mediaType: 'movie',
    year: 2022,
    characterName: 'Bruce Wayne',
    actorName: 'Robert Pattinson',
    directorName: 'Matt Reeves',
    creatorName: 'AeroEdits',
    category: 'Movie Scenepacks',
    quality: '1080p',
    codec: 'H.264',
    description: 'Quiet lonely night scenes, screaming in the rain, flare in floodwater, funeral confrontation, revenge monologue, dark aesthetic walking.',
    sourceUrl: 'https://scenepacks.com/pack/the-batman-2022-bruce-wayne',
    downloadPageUrl: 'https://scenepacks.com/download/the-batman-2022',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg',
    popularity: 99,
    downloadCount: 8900,
    publishedAt: '2023-01-20T10:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['the batman', 'bruce wayne', 'robert pattinson', 'rain', 'screaming in the rain', 'night', 'lonely', 'revenge', 'funeral'],
    vibeTags: ['rain', 'night', 'loneliness', 'anger', 'revenge', 'grief', 'badass', 'sad edit'],
  },
  {
    id: 'suits_the_batman_4k',
    sourceId: 'suits',
    externalId: 'the-batman-suits-4k',
    title: 'The Batman (2022) - Full Film Pack [4K Pro]',
    mediaTitle: 'The Batman',
    mediaType: 'movie',
    year: 2022,
    characterName: 'Bruce Wayne',
    actorName: 'Robert Pattinson',
    directorName: 'Matt Reeves',
    creatorName: 'SuitsTM',
    category: '4K Cinema',
    quality: '4K',
    codec: 'H.265 (HEVC)',
    description: 'Complete 4K raw clips, car chase in rain with Penguin, flare leading survivors, batmobile fire engine roar, highway explosion.',
    sourceUrl: 'https://suitstmscenepacks.com/pack/the-batman-4k',
    downloadPageUrl: 'https://suitstmscenepacks.com/download/the-batman-4k',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/74xTEgt7R36Fpooo50r9T25onhq.jpg',
    popularity: 94,
    downloadCount: 6420,
    publishedAt: '2023-04-12T16:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['the batman', '4k', 'batmobile', 'car chase', 'rain', 'fight', 'action', 'velocity'],
    vibeTags: ['fight', 'rain', 'night', 'badass', 'velocity', 'anger'],
  },

  // EUPHORIA (TV Series)
  {
    id: 'veel_euphoria_rue_bennett',
    sourceId: 'veel',
    externalId: 'euphoria-rue-bennett-s1-s2',
    title: 'Euphoria (Season 1 & 2) - Rue Bennett',
    mediaTitle: 'Euphoria',
    mediaType: 'tv',
    year: 2019,
    characterName: 'Rue Bennett',
    actorName: 'Zendaya',
    directorName: 'Sam Levinson',
    creatorName: 'Veel SCP',
    category: 'TV Series',
    quality: '1080p',
    codec: 'H.264',
    description: 'Girl crying alone in bedroom, panic attack, screaming argument with mother Leslie, sad breakup with Jules, glitter tears, emotional breakdown.',
    sourceUrl: 'https://veelscp.com/pack/euphoria-rue-bennett',
    downloadPageUrl: 'https://veelscp.com/dl/euphoria-rue',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/mez2Z3WqlPKNXpi7mWoiiE5guE9.jpg',
    popularity: 100,
    downloadCount: 12500,
    publishedAt: '2023-01-05T18:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['euphoria', 'rue bennett', 'zendaya', 'crying alone', 'panic attack', 'mother and daughter arguing', 'breakup', 'grief', 'sad edit'],
    vibeTags: ['sadness', 'grief', 'heartbreak', 'panic attack', 'argument', 'crying', 'sad edit', 'loneliness'],
  },
  {
    id: '411_euphoria_jules_maddy',
    sourceId: '411',
    externalId: 'euphoria-girls-pack',
    title: 'Euphoria - Maddy & Cassie Conflict Pack',
    mediaTitle: 'Euphoria',
    mediaType: 'tv',
    year: 2019,
    characterName: 'Maddy Perez',
    actorName: 'Alexa Demie',
    directorName: 'Sam Levinson',
    creatorName: '411 Crew',
    category: 'TV Series',
    quality: '1080p',
    codec: 'H.264',
    description: 'Someone realizes their best friend betrayed them, bathroom confrontation, luxury party looks, badass hallway walk, screaming betrayal.',
    sourceUrl: 'https://scenepacks.com/pack/euphoria-maddy-cassie',
    downloadPageUrl: 'https://scenepacks.com/download/euphoria-maddy-cassie',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/oKt4J3TFjWirVwBqoHyIvv5IImd.jpg',
    popularity: 91,
    downloadCount: 4700,
    publishedAt: '2023-02-18T11:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['euphoria', 'maddy perez', 'cassie', 'betrayal', 'friend betrayed', 'party', 'argument', 'badass entrance'],
    vibeTags: ['betrayal', 'argument', 'badass', 'party', 'confidence', 'heartbreak'],
  },

  // SPIDER-MAN
  {
    id: 'veel_spiderman_peter_parker',
    sourceId: 'veel',
    externalId: 'spiderman-peter-parker-trilogy',
    title: 'Spider-Man - Peter Parker Emotional & Loss Pack',
    mediaTitle: 'Spider-Man',
    mediaType: 'movie',
    year: 2021,
    characterName: 'Peter Parker',
    actorName: 'Tom Holland / Andrew Garfield',
    directorName: 'Jon Watts',
    creatorName: 'Veel SCP',
    category: 'Movie Scenepacks',
    quality: '1080p',
    codec: 'H.264',
    description: 'Losing someone you love, guy screaming in rain, holding dying Aunt May and Gwen Stacy, crying in rain on rooftop, heroic grief.',
    sourceUrl: 'https://veelscp.com/pack/spiderman-emotional-loss',
    downloadPageUrl: 'https://veelscp.com/dl/spiderman-grief',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg',
    popularity: 97,
    downloadCount: 9800,
    publishedAt: '2023-01-12T08:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['spider-man', 'spiderman', 'peter parker', 'grief', 'crying in the rain', 'loss of loved one', 'screaming', 'sad edit'],
    vibeTags: ['grief', 'sadness', 'rain', 'crying', 'anger', 'sad edit', 'fight'],
  },

  // SUCCESSION
  {
    id: 'suits_succession_kendall_roy',
    sourceId: 'suits',
    externalId: 'succession-kendall-roy-tragedy',
    title: 'Succession - Kendall Roy Breakdown & Betrayal',
    mediaTitle: 'Succession',
    mediaType: 'tv',
    year: 2018,
    characterName: 'Kendall Roy',
    actorName: 'Jeremy Strong',
    directorName: 'Mark Mylod',
    creatorName: 'SuitsTM',
    category: 'TV Scenepacks',
    quality: '1080p',
    codec: 'H.264',
    description: 'Character sitting alone after losing everything, realizing they were betrayed by family, crying in kitchen, listening to sad song in car, rooftop melancholy.',
    sourceUrl: 'https://suitstmscenepacks.com/pack/succession-kendall-roy',
    downloadPageUrl: 'https://suitstmscenepacks.com/download/succession-kendall',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/bcdUYUFk8GdpZJPiSAas9UeocLH.jpg',
    popularity: 92,
    downloadCount: 5200,
    publishedAt: '2023-03-25T13:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['succession', 'kendall roy', 'betrayal', 'breakdown', 'sitting alone after losing everything', 'sad edit', 'luxury', 'lonely'],
    vibeTags: ['betrayal', 'loneliness', 'sadness', 'heartbreak', 'sad edit', 'argument'],
  },

  // INTERSTELLAR (2014)
  {
    id: '411_interstellar_cooper',
    sourceId: '411',
    externalId: 'interstellar-2014-cooper-murph',
    title: 'Interstellar (2014) - Cooper & Murph Farewell & Messages',
    mediaTitle: 'Interstellar',
    mediaType: 'movie',
    year: 2014,
    characterName: 'Joseph Cooper',
    actorName: 'Matthew McConaughey',
    directorName: 'Christopher Nolan',
    creatorName: 'CinemaEdit411',
    category: 'Sci-Fi Masterpieces',
    quality: '1080p',
    codec: 'H.264',
    description: 'Crying watching 23 years of video messages, emotional goodbye in truck, father daughter reunion in hospital bed, clips for a sad edit.',
    sourceUrl: 'https://scenepacks.com/pack/interstellar-cooper-murph',
    downloadPageUrl: 'https://scenepacks.com/download/interstellar-2014',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    popularity: 98,
    downloadCount: 11200,
    publishedAt: '2023-01-08T19:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['interstellar', 'intersteller', 'cooper', 'murph', 'crying watching video messages', 'goodbye', 'reunion', 'emotional', 'sad edit'],
    vibeTags: ['grief', 'sadness', 'crying', 'reunion', 'sad edit', 'loneliness'],
  },

  // ARCANE
  {
    id: 'editpacks_arcane_jinx_vi',
    sourceId: 'editpacks',
    externalId: 'arcane-jinx-vi-tragedy',
    title: 'Arcane - Jinx & Vi Broken Bond Pack',
    mediaTitle: 'Arcane',
    mediaType: 'anime',
    year: 2021,
    characterName: 'Jinx / Powder',
    actorName: 'Ella Purnell',
    directorName: 'Pascal Charrue',
    creatorName: 'EditPacks Animation',
    category: 'Animated Scenepacks',
    quality: '1080p',
    codec: 'H.264',
    description: 'Girl crying after losing family, panic attack with flare, villain smiling through tears, tea party betrayal reveal, neon chaotic fight.',
    sourceUrl: 'https://editpacks.org/pack/arcane-jinx-vi',
    downloadPageUrl: 'https://editpacks.org/dl/arcane-jinx',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/q8eejQcg1bAqImEV8jh8RtBD4uH.jpg',
    popularity: 97,
    downloadCount: 8100,
    publishedAt: '2023-02-14T20:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['arcane', 'jinx', 'vi', 'powder', 'panic attack', 'crying alone', 'betrayal', 'villain', 'reunion', 'sad edit'],
    vibeTags: ['panic attack', 'sadness', 'betrayal', 'villain', 'crying', 'fight', 'sad edit'],
  },

  // PEAKY BLINDERS
  {
    id: 'suits_peaky_blinders_thomas_shelby',
    sourceId: 'suits',
    externalId: 'peaky-blinders-thomas-shelby-aura',
    title: 'Peaky Blinders - Thomas Shelby Badass & Revenge',
    mediaTitle: 'Peaky Blinders',
    mediaType: 'tv',
    year: 2013,
    characterName: 'Thomas Shelby',
    actorName: 'Cillian Murphy',
    directorName: 'Steven Knight',
    creatorName: 'SuitsTM',
    category: 'TV Series',
    quality: '1080p',
    codec: 'H.264',
    description: 'Confident entrance scene, slow motion walking with cigarette, cold revenge moments, badass aura clips for phonk and velocity edits.',
    sourceUrl: 'https://suitstmscenepacks.com/pack/peaky-blinders-thomas-shelby',
    downloadPageUrl: 'https://suitstmscenepacks.com/download/peaky-blinders-tommy',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/3UupR0nS9R6Di9letdz4ftX95GF.jpg',
    popularity: 95,
    downloadCount: 7800,
    publishedAt: '2023-01-28T14:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['peaky blinders', 'thomas shelby', 'cillian murphy', 'badass walking', 'confident entrance', 'revenge', 'velocity', 'hype'],
    vibeTags: ['badass', 'confidence', 'revenge', 'velocity', 'night'],
  },

  // BREAKING BAD
  {
    id: '411_breaking_bad_walter_white',
    sourceId: '411',
    externalId: 'breaking-bad-walter-white-despair',
    title: 'Breaking Bad - Walter White Crawl Space & Despair',
    mediaTitle: 'Breaking Bad',
    mediaType: 'tv',
    year: 2008,
    characterName: 'Walter White',
    actorName: 'Bryan Cranston',
    directorName: 'Vince Gilligan',
    creatorName: '411 Classic',
    category: 'TV Series',
    quality: '1080p',
    codec: 'H.264',
    description: 'Hysterical laughing in despair in crawl space, realizing they made a huge mistake, losing everything, desert screaming confrontation.',
    sourceUrl: 'https://scenepacks.com/pack/breaking-bad-walter-white',
    downloadPageUrl: 'https://scenepacks.com/download/breaking-bad-walter',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg',
    popularity: 96,
    downloadCount: 6900,
    publishedAt: '2023-02-05T10:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['breaking bad', 'walter white', 'bryan cranston', 'crawl space', 'laughing in despair', 'losing everything', 'villain', 'shock'],
    vibeTags: ['villain', 'sadness', 'panic attack', 'shock', 'betrayal'],
  },

  // THE LAST OF US
  {
    id: 'veel_the_last_of_us_joel_ellie',
    sourceId: 'veel',
    externalId: 'the-last-of-us-joel-ellie',
    title: 'The Last of Us (2023) - Joel Miller & Ellie Williams',
    mediaTitle: 'The Last of Us',
    mediaType: 'tv',
    year: 2023,
    characterName: 'Joel Miller',
    actorName: 'Pedro Pascal',
    directorName: 'Craig Mazin',
    creatorName: 'Veel SCP',
    category: 'TV Series',
    quality: '4K',
    codec: 'H.265 (HEVC)',
    description: 'Father crying holding dying daughter Sarah, quiet emotional bond in snow, hospital rescue rage, grief and protective violence.',
    sourceUrl: 'https://veelscp.com/pack/the-last-of-us-joel-ellie',
    downloadPageUrl: 'https://veelscp.com/dl/last-of-us-4k',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg',
    popularity: 97,
    downloadCount: 8400,
    publishedAt: '2023-03-15T15:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['the last of us', 'last of us', 'joel miller', 'pedro pascal', 'ellie', 'father crying', 'grief', 'daughter death', '4k'],
    vibeTags: ['grief', 'sadness', 'crying', 'fight', 'anger', 'sad edit'],
  },

  // OPPENHEIMER (2023)
  {
    id: 'editpacks_oppenheimer_4k',
    sourceId: 'editpacks',
    externalId: 'oppenheimer-2023-4k',
    title: 'Oppenheimer (2023) - J. Robert Oppenheimer [4K]',
    mediaTitle: 'Oppenheimer',
    mediaType: 'movie',
    year: 2023,
    characterName: 'J. Robert Oppenheimer',
    actorName: 'Cillian Murphy',
    directorName: 'Christopher Nolan',
    creatorName: 'EditPacks Master',
    category: '4K Cinema',
    quality: '4K',
    codec: 'H.265 (HEVC)',
    description: 'Panic attack in gymnasium applause scene, quiet loneliness by pond with Einstein, guilt and regret, blinding white explosion silence.',
    sourceUrl: 'https://editpacks.org/pack/oppenheimer-2023-4k',
    downloadPageUrl: 'https://editpacks.org/dl/oppenheimer-4k',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
    popularity: 95,
    downloadCount: 6700,
    publishedAt: '2023-08-01T12:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['oppenheimer', 'openheimer', 'cillian murphy', 'panic attack', 'guilt', 'regret', 'silence', '4k'],
    vibeTags: ['panic attack', 'loneliness', 'sadness', 'shock'],
  },

  // LA LA LAND (Romance / Heartbreak)
  {
    id: '411_la_la_land_ending',
    sourceId: '411',
    externalId: 'la-la-land-ending-nod',
    title: 'La La Land (2016) - Mia & Sebastian Epilogue & Look',
    mediaTitle: 'La La Land',
    mediaType: 'movie',
    year: 2016,
    characterName: 'Mia Dolan & Sebastian Wilder',
    actorName: 'Emma Stone / Ryan Gosling',
    directorName: 'Damien Chazelle',
    creatorName: '411 Romance',
    category: 'Romance Scenepacks',
    quality: '1080p',
    codec: 'H.264',
    description: 'Couple looking at each other without talking, romantic eye contact, final bittersweet smile, nostalgic flashback of what could have been.',
    sourceUrl: 'https://scenepacks.com/pack/la-la-land-epilogue',
    downloadPageUrl: 'https://scenepacks.com/download/la-la-land',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/nlPCdZlHtRNcF6C9hzUH4ebmV1w.jpg',
    popularity: 93,
    downloadCount: 5600,
    publishedAt: '2023-02-12T17:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['la la land', 'ryan gosling', 'emma stone', 'romantic eye contact', 'looking at each other without talking', 'bittersweet smile', 'heartbreak', 'nostalgia'],
    vibeTags: ['romance', 'heartbreak', 'nostalgia', 'sadness', 'sad edit'],
  },

  // STRANGER THINGS
  {
    id: 'veel_stranger_things_eleven_max',
    sourceId: 'veel',
    externalId: 'stranger-things-s4-emotional',
    title: 'Stranger Things 4 - Max & Eleven Emotional Moments',
    mediaTitle: 'Stranger Things',
    mediaType: 'tv',
    year: 2016,
    characterName: 'Eleven & Max Mayfield',
    actorName: 'Millie Bobby Brown / Sadie Sink',
    directorName: 'The Duffer Brothers',
    creatorName: 'Veel SCP',
    category: 'TV Series',
    quality: '1080p',
    codec: 'H.264',
    description: 'Dear Billy cemetery scene, running up that hill, girl crying after losing someone, scary red mindscape, friendship goodbye.',
    sourceUrl: 'https://veelscp.com/pack/stranger-things-max-eleven',
    downloadPageUrl: 'https://veelscp.com/dl/stranger-things-s4',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
    popularity: 96,
    downloadCount: 7600,
    publishedAt: '2023-01-22T21:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['stranger things', 'strangerthings', 'eleven', 'max mayfield', 'grief', 'sad edit', 'crying', 'friendship', 'running up that hill'],
    vibeTags: ['grief', 'sadness', 'crying', 'friendship', 'fight', 'sad edit'],
  },

  // FIGHT CLUB (1999)
  {
    id: 'suits_fight_club_tyler_durden',
    sourceId: 'suits',
    externalId: 'fight-club-tyler-durden-4k',
    title: 'Fight Club (1999) - Tyler Durden & The Narrator [4K]',
    mediaTitle: 'Fight Club',
    mediaType: 'movie',
    year: 1999,
    characterName: 'Tyler Durden / The Narrator',
    actorName: 'Brad Pitt / Edward Norton',
    directorName: 'David Fincher',
    creatorName: 'SuitsTM',
    category: '4K Cinema',
    quality: '4K',
    codec: 'H.265 (HEVC)',
    description: 'Badass sigma clips, realizing they are the same person, bloody smile in basement, building collapse holding hands ending, monologue about consumerism.',
    sourceUrl: 'https://suitstmscenepacks.com/pack/fight-club-4k',
    downloadPageUrl: 'https://suitstmscenepacks.com/download/fight-club-4k',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/hZkgoQYus5vegHoetLkCJzb17zJ.jpg',
    popularity: 97,
    downloadCount: 8900,
    publishedAt: '2023-05-10T14:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['fight club', 'tyler durden', 'brad pitt', 'edward norton', 'badass', 'sigma', 'fight', 'blood', 'mind blown', 'velocity'],
    vibeTags: ['fight', 'badass', 'confidence', 'blood', 'velocity', 'shock'],
  },

  // DUNE: PART TWO (2024)
  {
    id: 'veel_dune_part_two_paul_atreides',
    sourceId: 'veel',
    externalId: 'dune-part-two-paul-atreides-4k',
    title: 'Dune: Part Two (2024) - Paul Atreides & Feyd-Rautha [4K HDR]',
    mediaTitle: 'Dune: Part Two',
    mediaType: 'movie',
    year: 2024,
    characterName: 'Paul Atreides',
    actorName: 'Timothée Chalamet / Austin Butler',
    directorName: 'Denis Villeneuve',
    creatorName: 'Veel SCP Master',
    category: '4K Cinema',
    quality: '4K',
    codec: 'H.265 (HEVC)',
    description: 'Silence speech in war council, riding the sandworm, knife duel with Feyd-Rautha, lead them to paradise speech, holy war begins.',
    sourceUrl: 'https://veelscp.com/pack/dune-2-4k',
    downloadPageUrl: 'https://veelscp.com/dl/dune-2-4k',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    popularity: 99,
    downloadCount: 14200,
    publishedAt: '2024-03-20T18:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['dune', 'dune 2', 'paul atreides', 'timothee chalamet', 'feyd-rautha', 'austin butler', 'sandworm', 'badass entrance', 'power', '4k'],
    vibeTags: ['badass', 'confidence', 'fight', 'anger', 'velocity'],
  },

  // THE BOYS (2019)
  {
    id: '411_the_boys_homelander_butcher',
    sourceId: '411',
    externalId: 'the-boys-homelander-butcher',
    title: 'The Boys - Homelander & Billy Butcher Unhinged Pack',
    mediaTitle: 'The Boys',
    mediaType: 'tv',
    year: 2019,
    characterName: 'Homelander & Billy Butcher',
    actorName: 'Antony Starr / Karl Urban',
    directorName: 'Eric Kripke',
    creatorName: '411 Archive',
    category: 'TV Series',
    quality: '1080p',
    codec: 'H.264',
    description: 'Unhinged laser eyes, villain smiling creepily in mirror, covered in blood laughing, violent revenge, screaming oi cunt.',
    sourceUrl: 'https://scenepacks.com/pack/the-boys-homelander-butcher',
    downloadPageUrl: 'https://scenepacks.com/download/the-boys',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg',
    popularity: 98,
    downloadCount: 11800,
    publishedAt: '2023-06-15T16:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['the boys', 'homelander', 'billy butcher', 'antony starr', 'unhinged', 'laser eyes', 'villain', 'covered in blood', 'revenge'],
    vibeTags: ['villain', 'blood', 'badass', 'anger', 'fight', 'shock'],
  },

  // BLADE RUNNER 2049 (2017)
  {
    id: 'editpacks_blade_runner_2049_officer_k',
    sourceId: 'editpacks',
    externalId: 'blade-runner-2049-officer-k',
    title: 'Blade Runner 2049 (2017) - Officer K / Joe [4K]',
    mediaTitle: 'Blade Runner 2049',
    mediaType: 'movie',
    year: 2017,
    characterName: 'Officer K / Joe',
    actorName: 'Ryan Gosling',
    directorName: 'Denis Villeneuve',
    creatorName: 'EditPacks Master',
    category: '4K Cinema',
    quality: '4K',
    codec: 'H.265 (HEVC)',
    description: 'You look lonely giant holographic Joi scene, screaming baseline test, lying on steps in snow ending, quiet melancholic walking.',
    sourceUrl: 'https://editpacks.org/pack/blade-runner-2049-officer-k',
    downloadPageUrl: 'https://editpacks.org/dl/blade-runner-4k',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
    popularity: 96,
    downloadCount: 9300,
    publishedAt: '2023-04-18T19:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['blade runner 2049', 'blade runner', 'officer k', 'ryan gosling', 'you look lonely', 'joi', 'lonely', 'sad edit', 'snow ending'],
    vibeTags: ['loneliness', 'sadness', 'nostalgia', 'sad edit', 'night'],
  },

  // WHIPLASH (2014)
  {
    id: 'suits_whiplash_andrew_neiman',
    sourceId: 'suits',
    externalId: 'whiplash-andrew-neiman-fletcher',
    title: 'Whiplash (2014) - Andrew Neiman & Fletcher Final Solo',
    mediaTitle: 'Whiplash',
    mediaType: 'movie',
    year: 2014,
    characterName: 'Andrew Neiman & Terence Fletcher',
    actorName: 'Miles Teller / J.K. Simmons',
    directorName: 'Damien Chazelle',
    creatorName: 'SuitsTM',
    category: 'Movie Scenepacks',
    quality: '1080p',
    codec: 'H.264',
    description: 'Blood on drum cymbals, intense bleeding fingers, caravan final solo smiling nod at Fletcher, obsessively practicing until exhaustion.',
    sourceUrl: 'https://suitstmscenepacks.com/pack/whiplash-final-solo',
    downloadPageUrl: 'https://suitstmscenepacks.com/download/whiplash',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg',
    popularity: 95,
    downloadCount: 7400,
    publishedAt: '2023-07-11T13:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['whiplash', 'andrew neiman', 'miles teller', 'fletcher', 'jk simmons', 'drum solo', 'blood', 'obsession', 'badass', 'velocity'],
    vibeTags: ['blood', 'badass', 'anger', 'confidence', 'velocity'],
  },

  // JUJUTSU KAISEN (Anime)
  {
    id: 'editpacks_jjk_gojo_sukuna',
    sourceId: 'editpacks',
    externalId: 'jujutsu-kaisen-gojo-sukuna-4k',
    title: 'Jujutsu Kaisen - Gojo Satoru & Sukuna Domain Expansion [4K]',
    mediaTitle: 'Jujutsu Kaisen',
    mediaType: 'anime',
    year: 2020,
    characterName: 'Gojo Satoru & Ryomen Sukuna',
    actorName: 'Yuichi Nakamura / Junichi Suwabe',
    directorName: 'Sunghoo Park',
    creatorName: 'EditPacks Animation',
    category: 'Anime Scenepacks',
    quality: '4K',
    codec: 'H.265 (HEVC)',
    description: 'Hollow Purple, Unlimited Void domain expansion, Malevolent Shrine, Sukuna vs Mahoraga Shibuya arc, Gojo blindfold pull.',
    sourceUrl: 'https://editpacks.org/pack/jjk-gojo-sukuna-4k',
    downloadPageUrl: 'https://editpacks.org/dl/jjk-4k',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/qpin8cASXEVtwhzNsprHYFiOAGk.jpg',
    popularity: 100,
    downloadCount: 19800,
    publishedAt: '2023-11-15T18:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['jujutsu kaisen', 'jjk', 'gojo satoru', 'sukuna', 'domain expansion', 'hollow purple', 'anime', 'badass', 'shibuya', '4k'],
    vibeTags: ['badass', 'confidence', 'fight', 'anger', 'velocity'],
  },

  // ATTACK ON TITAN (Anime)
  {
    id: '411_aot_eren_levi',
    sourceId: '411',
    externalId: 'attack-on-titan-eren-levi-final',
    title: 'Attack on Titan - Eren Yeager & Levi Ackerman Rumbling',
    mediaTitle: 'Attack on Titan',
    mediaType: 'anime',
    year: 2013,
    characterName: 'Eren Yeager & Levi Ackerman',
    actorName: 'Yuki Kaji / Hiroshi Kamiya',
    directorName: 'Tetsuro Araki',
    creatorName: '411 Anime',
    category: 'Anime Scenepacks',
    quality: '1080p',
    codec: 'H.264',
    description: 'Freedom speech in clouds, Levi vs Beast Titan forest chase, Rumbling titan march, Eren crying breakdown, Declaration of War transformation.',
    sourceUrl: 'https://scenepacks.com/pack/attack-on-titan-eren-levi',
    downloadPageUrl: 'https://scenepacks.com/download/aot-final',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/hTP1DtLGFamjfu8WqjnuQdP1n4i.jpg',
    popularity: 99,
    downloadCount: 16500,
    publishedAt: '2023-12-01T20:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['attack on titan', 'aot', 'eren yeager', 'levi ackerman', 'rumbling', 'anime', 'grief', 'fight', 'revenge', 'sad edit'],
    vibeTags: ['grief', 'revenge', 'badass', 'fight', 'anger', 'sad edit'],
  },

  // DEMON SLAYER (Anime)
  {
    id: 'veel_demon_slayer_rengoku_akaza',
    sourceId: 'veel',
    externalId: 'demon-slayer-mugen-train-4k',
    title: 'Demon Slayer - Rengoku & Akaza Mugen Train [4K HDR]',
    mediaTitle: 'Demon Slayer',
    mediaType: 'anime',
    year: 2019,
    characterName: 'Kyojuro Rengoku & Akaza',
    actorName: 'Satoshi Hino / Akira Ishida',
    directorName: 'Haruo Sotozaki',
    creatorName: 'Veel SCP Master',
    category: '4K Cinema',
    quality: '4K',
    codec: 'H.265 (HEVC)',
    description: 'Set your heart ablaze 9th form Rengoku, Akaza destructive kill needle, Tanjiro crying screaming at Akaza running into sun, 60fps high bitrate.',
    sourceUrl: 'https://veelscp.com/pack/demon-slayer-rengoku-4k',
    downloadPageUrl: 'https://veelscp.com/dl/rengoku-4k',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg',
    popularity: 98,
    downloadCount: 15400,
    publishedAt: '2023-09-10T12:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['demon slayer', 'kimetsu no yaiba', 'rengoku', 'akaza', 'tanjiro', 'mugen train', 'anime', 'crying', 'grief', '4k'],
    vibeTags: ['grief', 'sadness', 'crying', 'fight', 'badass', 'sad edit'],
  },

  // AMERICAN PSYCHO (2000)
  {
    id: 'suits_american_psycho_patrick_bateman',
    sourceId: 'suits',
    externalId: 'american-psycho-patrick-bateman-4k',
    title: 'American Psycho (2000) - Patrick Bateman Sigma Routine [4K]',
    mediaTitle: 'American Psycho',
    mediaType: 'movie',
    year: 2000,
    characterName: 'Patrick Bateman',
    actorName: 'Christian Bale',
    directorName: 'Mary Harron',
    creatorName: 'SuitsTM',
    category: '4K Cinema',
    quality: '4K',
    codec: 'H.265 (HEVC)',
    description: 'Morning skincare routine, business card comparison sweating, raincoat axe walking with Huey Lewis, unhinged confession call in phone booth.',
    sourceUrl: 'https://suitstmscenepacks.com/pack/american-psycho-4k',
    downloadPageUrl: 'https://suitstmscenepacks.com/download/american-psycho',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/5oaMV2q0qzxkIW2ukU3lldLu5q2.jpg',
    popularity: 99,
    downloadCount: 18200,
    publishedAt: '2023-04-05T15:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['american psycho', 'patrick bateman', 'christian bale', 'sigma', 'business card', 'skincare routine', 'unhinged', 'badass', 'phonk', '4k'],
    vibeTags: ['badass', 'confidence', 'villain', 'luxury', 'blood', 'velocity'],
  },

  // JOKER (2019)
  {
    id: '411_joker_arthur_fleck',
    sourceId: '411',
    externalId: 'joker-2019-arthur-fleck-4k',
    title: 'Joker (2019) - Arthur Fleck Stair Dance & Descent [4K]',
    mediaTitle: 'Joker',
    mediaType: 'movie',
    year: 2019,
    characterName: 'Arthur Fleck / Joker',
    actorName: 'Joaquin Phoenix',
    directorName: 'Todd Phillips',
    creatorName: '411 Archive',
    category: 'Movie Scenepacks',
    quality: '4K',
    codec: 'H.265 (HEVC)',
    description: 'Iconic stair dance scene with cigarette, bathroom solo dance, Murray Franklin talk show confrontation, laughing in sorrow, crying with clown makeup.',
    sourceUrl: 'https://scenepacks.com/pack/joker-2019-arthur-fleck',
    downloadPageUrl: 'https://scenepacks.com/download/joker-4k',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
    popularity: 98,
    downloadCount: 17300,
    publishedAt: '2023-05-18T16:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['joker', 'arthur fleck', 'joaquin phoenix', 'stair dance', 'clown', 'sadness', 'villain', 'laughing in despair', 'crying', 'sad edit', '4k'],
    vibeTags: ['villain', 'sadness', 'loneliness', 'badass', 'shock', 'sad edit'],
  },

  // WEDNESDAY (2022)
  {
    id: 'veel_wednesday_addams_dance',
    sourceId: 'veel',
    externalId: 'wednesday-addams-dance-cello',
    title: "Wednesday - Wednesday Addams Rave'N Dance & Cello",
    mediaTitle: 'Wednesday',
    mediaType: 'tv',
    year: 2022,
    characterName: 'Wednesday Addams',
    actorName: 'Jenna Ortega',
    directorName: 'Tim Burton',
    creatorName: 'Veel SCP',
    category: 'TV Series',
    quality: '1080p',
    codec: 'H.264',
    description: "Goo Goo Muck Rave'N black dress dance, playing Paint It Black on cello on balcony, cold stare unblinking moments, fencing duel with Bianca.",
    sourceUrl: 'https://veelscp.com/pack/wednesday-addams',
    downloadPageUrl: 'https://veelscp.com/dl/wednesday',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg',
    popularity: 97,
    downloadCount: 13900,
    publishedAt: '2023-01-30T14:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['wednesday', 'wednesday addams', 'jenna ortega', 'dance', 'cello', 'paint it black', 'goth', 'badass', 'unblinking', 'velocity'],
    vibeTags: ['badass', 'confidence', 'night', 'velocity', 'party'],
  },

  // CYBERPUNK: EDGERUNNERS (2022)
  {
    id: 'editpacks_cyberpunk_david_lucy',
    sourceId: 'editpacks',
    externalId: 'cyberpunk-edgerunners-david-lucy',
    title: 'Cyberpunk: Edgerunners - David Martinez & Lucy Moon Scene',
    mediaTitle: 'Cyberpunk: Edgerunners',
    mediaType: 'anime',
    year: 2022,
    characterName: 'David Martinez & Lucy',
    actorName: 'KENN / Aoi Yuuki',
    directorName: 'Hiroyuki Imaishi',
    creatorName: 'EditPacks Animation',
    category: 'Anime Scenepacks',
    quality: '1080p',
    codec: 'H.264',
    description: 'I Really Want to Stay at Your House, moon BD simulation, Sandevistan velocity dash, David crying for mom, Arasaka tower final sacrifice smile.',
    sourceUrl: 'https://editpacks.org/pack/cyberpunk-edgerunners',
    downloadPageUrl: 'https://editpacks.org/dl/edgerunners',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/bRE6zX4iOAejLOQCHryoV5WNu8G.jpg',
    popularity: 99,
    downloadCount: 18700,
    publishedAt: '2023-02-28T21:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['cyberpunk', 'cyberpunk edgerunners', 'david martinez', 'lucy', 'stay at your house', 'moon scene', 'sandevistan', 'grief', 'sad edit', 'anime'],
    vibeTags: ['grief', 'sadness', 'crying', 'romance', 'velocity', 'badass', 'sad edit'],
  },

  // DRIVE (2011)
  {
    id: 'suits_drive_ryan_gosling',
    sourceId: 'suits',
    externalId: 'drive-2011-ryan-gosling-real-hero',
    title: 'Drive (2011) - The Driver / Ryan Gosling Synthwave [1080p]',
    mediaTitle: 'Drive',
    mediaType: 'movie',
    year: 2011,
    characterName: 'The Driver',
    actorName: 'Ryan Gosling',
    directorName: 'Nicolas Winding Refn',
    creatorName: 'SuitsTM',
    category: 'Movie Scenepacks',
    quality: '1080p',
    codec: 'H.264',
    description: 'Scorpion jacket night driving, elevator slow motion kiss and stomp, Nightcall opening credits, quiet staring tooth pick moments, literal me sigma.',
    sourceUrl: 'https://suitstmscenepacks.com/pack/drive-2011',
    downloadPageUrl: 'https://suitstmscenepacks.com/download/drive',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/hoyAALgfmjMEK7O1wZ4r8wT91RP.jpg',
    popularity: 96,
    downloadCount: 11400,
    publishedAt: '2023-03-12T17:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['drive', 'ryan gosling', 'the driver', 'scorpion jacket', 'nightcall', 'synthwave', 'sigma', 'elevator', 'night', 'lonely'],
    vibeTags: ['night', 'loneliness', 'badass', 'romance', 'blood'],
  },

  // HOUSE OF THE DRAGON (2022)
  {
    id: '411_house_of_the_dragon_daemon',
    sourceId: '411',
    externalId: 'house-of-the-dragon-daemon-targaryen',
    title: 'House of the Dragon - Daemon Targaryen & Rhaenyra [4K]',
    mediaTitle: 'House of the Dragon',
    mediaType: 'tv',
    year: 2022,
    characterName: 'Daemon Targaryen',
    actorName: 'Matt Smith',
    directorName: 'Miguel Sapochnik',
    creatorName: '411 Archive',
    category: 'TV Series',
    quality: '4K',
    codec: 'H.265 (HEVC)',
    description: 'Caraxes blood dragon roar, Stepstones arrow solo charge, picking up the crown for King Viserys, Dark Sister beheading, cold smirk.',
    sourceUrl: 'https://scenepacks.com/pack/house-of-the-dragon-daemon',
    downloadPageUrl: 'https://scenepacks.com/download/hotd-daemon',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/577eXC8wFQT0eUrJcgznSiFPRmk.jpg',
    popularity: 97,
    downloadCount: 12600,
    publishedAt: '2023-04-20T19:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['house of the dragon', 'hotd', 'daemon targaryen', 'matt smith', 'rhaenyra', 'caraxes', 'dragon', 'badass', 'fight', '4k'],
    vibeTags: ['badass', 'confidence', 'fight', 'anger', 'villain', 'luxury'],
  },

  // BETTER CALL SAUL (2015)
  {
    id: 'veel_better_call_saul_lalo',
    sourceId: 'veel',
    externalId: 'better-call-saul-saul-lalo',
    title: 'Better Call Saul - Saul Goodman & Lalo Salamanca Tension',
    mediaTitle: 'Better Call Saul',
    mediaType: 'tv',
    year: 2015,
    characterName: 'Jimmy McGill / Saul Goodman & Lalo Salamanca',
    actorName: 'Bob Odenkirk / Tony Dalton',
    directorName: 'Peter Gould',
    creatorName: 'Veel SCP',
    category: 'TV Series',
    quality: '1080p',
    codec: 'H.264',
    description: 'Tell me again scene with Kim Wexler, Lalo smiling in candlelight apartment, lightning bolts shooting from fingertips speech, desert Bagman survival.',
    sourceUrl: 'https://veelscp.com/pack/better-call-saul',
    downloadPageUrl: 'https://veelscp.com/dl/bcs',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/rfxryDIv8huejujg4JueDJx8zCz.jpg',
    popularity: 96,
    downloadCount: 9800,
    publishedAt: '2023-05-25T11:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['better call saul', 'saul goodman', 'jimmy mcgill', 'lalo salamanca', 'bob odenkirk', 'tony dalton', 'tension', 'badass', 'villain'],
    vibeTags: ['villain', 'badass', 'confidence', 'shock', 'panic attack'],
  },

  // TOP GUN: MAVERICK (2022)
  {
    id: 'editpacks_top_gun_maverick_4k',
    sourceId: 'editpacks',
    externalId: 'top-gun-maverick-pete-mitchell-4k',
    title: 'Top Gun: Maverick (2022) - Pete Mitchell Mach 10 & Dogfight [4K]',
    mediaTitle: 'Top Gun: Maverick',
    mediaType: 'movie',
    year: 2022,
    characterName: 'Pete "Maverick" Mitchell',
    actorName: 'Tom Cruise',
    directorName: 'Joseph Kosinski',
    creatorName: 'EditPacks Master',
    category: '4K Cinema',
    quality: '4K',
    codec: 'H.265 (HEVC)',
    description: 'Darkstar Mach 10 speed run in atmosphere, canyon run 2 minute 15 second test, F-14 dogfight with 5th gen fighters, sunset beach football.',
    sourceUrl: 'https://editpacks.org/pack/top-gun-maverick-4k',
    downloadPageUrl: 'https://editpacks.org/dl/maverick-4k',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/AaV1YIdWKnjAIAOe8UUKBFm327v.jpg',
    popularity: 98,
    downloadCount: 14100,
    publishedAt: '2023-06-08T15:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['top gun', 'top gun maverick', 'pete mitchell', 'tom cruise', 'darkstar', 'fighter jet', 'dogfight', 'badass', 'velocity', '4k'],
    vibeTags: ['badass', 'confidence', 'velocity', 'party'],
  },

  // THE WOLF OF WALL STREET (2013)
  {
    id: '411_wolf_of_wall_street_belfort',
    sourceId: '411',
    externalId: 'the-wolf-of-wall-street-jordan-belfort',
    title: 'The Wolf of Wall Street (2013) - Jordan Belfort Hype Speeches',
    mediaTitle: 'The Wolf of Wall Street',
    mediaType: 'movie',
    year: 2013,
    characterName: 'Jordan Belfort',
    actorName: 'Leonardo DiCaprio',
    directorName: 'Martin Scorsese',
    creatorName: '411 Archive',
    category: 'Movie Scenepacks',
    quality: '1080p',
    codec: 'H.264',
    description: 'Im not leaving speech microphone drop, Matthew McConaughey chest thump restaurant rhythm, luxury yacht in storm, motivational hype phonk clips.',
    sourceUrl: 'https://scenepacks.com/pack/wolf-of-wall-street',
    downloadPageUrl: 'https://scenepacks.com/download/wolf-wall-street',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/cWUOv3H7YFwvKeaQhoAQTLLpo9Z.jpg',
    popularity: 97,
    downloadCount: 13200,
    publishedAt: '2023-07-01T12:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['the wolf of wall street', 'wolf of wall street', 'jordan belfort', 'leonardo dicaprio', 'im not leaving', 'chest thump', 'luxury', 'hype', 'phonk'],
    vibeTags: ['confidence', 'party', 'luxury', 'badass', 'velocity'],
  },

  // CRISTIANO RONALDO (Sports / Football)
  {
    id: 'veel_cristiano_ronaldo_ucl',
    sourceId: 'veel',
    externalId: 'cristiano-ronaldo-real-madrid-prime',
    title: 'Cristiano Ronaldo - Real Madrid UCL Prime & Calma [1080p 60fps]',
    mediaTitle: 'Cristiano Ronaldo',
    mediaType: 'sports',
    year: 2017,
    characterName: 'Cristiano Ronaldo (CR7)',
    actorName: 'Cristiano Ronaldo',
    directorName: 'Champions League',
    creatorName: 'Veel SCP Sports',
    category: 'Sports & Athletes',
    quality: '1080p',
    codec: 'H.264',
    description: 'Calma Camp Nou celebration, bicycle kick vs Juventus in Turin, hat trick vs Atletico Madrid comeback, Siuuu celebration in rain, velocity 60fps raw clips.',
    sourceUrl: 'https://veelscp.com/pack/cristiano-ronaldo-prime',
    downloadPageUrl: 'https://veelscp.com/dl/cr7-prime',
    thumbnailUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=800&auto=format&fit=crop&q=80',
    popularity: 99,
    downloadCount: 22000,
    publishedAt: '2023-08-15T10:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['cristiano ronaldo', 'cr7', 'ronaldo', 'real madrid', 'ucl', 'calma', 'bicycle kick', 'football', 'soccer', 'sports', 'velocity', 'badass'],
    vibeTags: ['badass', 'confidence', 'velocity', 'hype', 'party'],
  },

  // LIONEL MESSI (Sports / Football)
  {
    id: 'editpacks_lionel_messi_world_cup',
    sourceId: 'editpacks',
    externalId: 'lionel-messi-world-cup-2022-4k',
    title: 'Lionel Messi - World Cup Qatar 2022 Masterpiece [4K 60fps]',
    mediaTitle: 'Lionel Messi',
    mediaType: 'sports',
    year: 2022,
    characterName: 'Lionel Messi (LM10)',
    actorName: 'Lionel Messi',
    directorName: 'FIFA World Cup',
    creatorName: 'EditPacks Sports',
    category: 'Sports & Athletes',
    quality: '4K',
    codec: 'H.265 (HEVC)',
    description: 'Lifting World Cup trophy in golden bisht, Mexico long range strike, Gvardiol assist turn on wing, crying hugging mother on pitch after victory.',
    sourceUrl: 'https://editpacks.org/pack/lionel-messi-world-cup-4k',
    downloadPageUrl: 'https://editpacks.org/dl/messi-4k',
    thumbnailUrl: 'https://images.unsplash.com/photo-1579952363873-27f3bade9f55?w=800&auto=format&fit=crop&q=80',
    popularity: 99,
    downloadCount: 24500,
    publishedAt: '2023-01-10T18:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['lionel messi', 'messi', 'lm10', 'world cup 2022', 'argentina', 'trophy', 'football', 'soccer', 'sports', 'grief', 'reunion', '4k', 'velocity'],
    vibeTags: ['badass', 'confidence', 'reunion', 'grief', 'crying', 'velocity', 'party'],
  }
];

// Initialize packs with local pre-computed embedding vectors
export const MOCK_PACKS: Pack[] = RAW_PACKS_DATA.map(pack => {
  const embeddingText = [
    pack.title,
    pack.mediaTitle,
    pack.characterName || '',
    pack.actorName || '',
    pack.description || '',
    ...(pack.tags || []),
    ...(pack.vibeTags || [])
  ].join(' ');
  return {
    ...pack,
    embedding: generateLocalEmbedding(embeddingText),
  };
});

export function getMockDiagnostics(): DiagnosticsData {
  const packsPerSource: Record<string, number> = {
    '411': MOCK_PACKS.filter(p => p.sourceId === '411').length,
    'veel': MOCK_PACKS.filter(p => p.sourceId === 'veel').length,
    'editpacks': MOCK_PACKS.filter(p => p.sourceId === 'editpacks').length,
    'suits': MOCK_PACKS.filter(p => p.sourceId === 'suits').length,
  };

  return {
    totalIndexedPacks: MOCK_PACKS.length * 280, // Scaled for display representation
    packsPerSource: packsPerSource as any,
    lastCrawlTimes: {
      '411': new Date(Date.now() - 3600000 * 4).toISOString(),
      'veel': new Date(Date.now() - 3600000 * 2).toISOString(),
      'editpacks': new Date(Date.now() - 3600000 * 7).toISOString(),
      'suits': new Date(Date.now() - 3600000 * 5).toISOString(),
    },
    activeSources: INITIAL_SOURCES,
    inactiveLinksCount: 0,
    duplicateGroupCount: 6,
    averageSearchLatencyMs: 18,
    failedCrawlPages: [],
    tagCount: 142,
    isLiveIndex: false,
  };
}
