import { Pack, Source, DiagnosticsData } from '../types';
import { generateLocalEmbedding } from '../search/vector-search';

export const INITIAL_SOURCES: Source[] = [
  {
    id: '411',
    name: '411 Scenepacks',
    baseUrl: 'https://scenepacks.com',
    badgeName: '411 Scenepacks',
    badgeColor: 'bg-blue-500/15 text-blue-400 border border-blue-500/30',
    enabled: true,
    lastCrawledAt: new Date(Date.now() - 3600000 * 2).toISOString(),
    packCount: 5820,
  },
  {
    id: 'veel',
    name: 'Veel Scenepacks',
    baseUrl: 'https://veelscp.com',
    badgeName: 'Veel SCP',
    badgeColor: 'bg-pink-500/15 text-pink-400 border border-pink-500/30',
    enabled: true,
    lastCrawledAt: new Date(Date.now() - 3600000 * 1).toISOString(),
    packCount: 3150,
  },
  {
    id: 'editpacks',
    name: 'EditPacks',
    baseUrl: 'https://editpacks.org',
    badgeName: 'EditPacks',
    badgeColor: 'bg-emerald-500/15 text-emerald-400 border border-emerald-500/30',
    enabled: true,
    lastCrawledAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    packCount: 1680,
  },
  {
    id: 'suits',
    name: 'SuitsTM Scenepacks',
    baseUrl: 'https://suitstmscenepacks.com',
    badgeName: 'Suits™',
    badgeColor: 'bg-amber-500/15 text-amber-400 border border-amber-500/30',
    enabled: true,
    lastCrawledAt: new Date(Date.now() - 3600000 * 3).toISOString(),
    packCount: 140,
  },
];

const RAW_PACKS_DATA: Omit<Pack, 'embedding'>[] = [
  // CRUELLA (2021) - Multiple packs from 411 and Veel
  {
    id: '411_cruella_estella_1080p',
    sourceId: '411',
    externalId: 'cruella-estella-1080p',
    title: 'Cruella (2021) - Estella Scenepack',
    mediaTitle: 'Cruella',
    mediaType: 'movie',
    year: 2021,
    characterName: 'Estella',
    actorName: 'Emma Stone',
    directorName: 'Craig Gillespie',
    creatorName: '411 Archive',
    category: 'Movie Scenepacks',
    quality: '1080p',
    codec: 'H.264',
    description: 'Estella transformation scenes, discovering Baroness killed her mother at the cliff, grief at fountain, revenge fashion entrance, red dress fire scene.',
    sourceUrl: 'https://scenepacks.com/pack/cruella-2021-estella',
    downloadPageUrl: 'https://scenepacks.com/download/cruella-estella-1080p',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/rTh4K5uw9HypmpGslcKd4QfHl93.jpg',
    popularity: 98,
    downloadCount: 4320,
    publishedAt: '2023-01-15T12:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['cruella', 'estella', 'emma stone', 'mother death reveal', 'revenge', 'badass entrance', 'grief', 'betrayal', 'fashion'],
    vibeTags: ['grief', 'revenge', 'betrayal', 'badass', 'confident', 'party', 'sadness', 'murder discovery'],
  },
  {
    id: 'veel_cruella_2021_4k',
    sourceId: 'veel',
    externalId: 'cruella-2021-4k-hdr',
    title: 'Cruella (2021) - Cruella De Vil [4K HDR]',
    mediaTitle: 'Cruella',
    mediaType: 'movie',
    year: 2021,
    characterName: 'Cruella',
    actorName: 'Emma Stone',
    directorName: 'Craig Gillespie',
    creatorName: 'Veel SCP Master',
    category: '4K Cinema',
    quality: '4K',
    codec: 'H.265 (HEVC)',
    description: 'High bitrate 4K clips of Cruella revenge gala entrances, dumpster truck trash dress, finding out truth about mother, villain laugh.',
    sourceUrl: 'https://veelscp.com/pack/cruella-2021-4k',
    downloadPageUrl: 'https://veelscp.com/dl/cruella-2021-4k',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/rTh4K5uw9HypmpGslcKd4QfHl93.jpg',
    popularity: 96,
    downloadCount: 5120,
    publishedAt: '2023-02-10T14:30:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['cruella', 'emma stone', 'villain', 'badass', '4k', 'hevc', 'fashion', 'gala', 'revenge', 'mother murder reveal'],
    vibeTags: ['villain', 'badass', 'revenge', 'confidence', 'party', 'luxury', 'velocity'],
  },
  {
    id: '411_cruella_baroness',
    sourceId: '411',
    externalId: 'cruella-baroness-von-hellman',
    title: 'Cruella (2021) - Baroness von Hellman',
    mediaTitle: 'Cruella',
    mediaType: 'movie',
    year: 2021,
    characterName: 'Baroness von Hellman',
    actorName: 'Emma Thompson',
    directorName: 'Craig Gillespie',
    creatorName: '411 Team',
    category: 'Villain Scenepacks',
    quality: '1080p',
    codec: 'H.264',
    description: 'Baroness cruel scenes, narcissist boss energy, dog whistle cliff scene, arrogant smiles, cold betrayal scenes.',
    sourceUrl: 'https://scenepacks.com/pack/cruella-baroness',
    downloadPageUrl: 'https://scenepacks.com/download/cruella-baroness',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/rTh4K5uw9HypmpGslcKd4QfHl93.jpg',
    popularity: 82,
    downloadCount: 1840,
    publishedAt: '2023-03-01T09:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['cruella', 'baroness', 'emma thompson', 'villain', 'narcissist', 'luxury', 'betrayal'],
    vibeTags: ['villain', 'confident', 'betrayal', 'party', 'badass'],
  },

  // THE BATMAN (2022)
  {
    id: '411_the_batman_bruce_wayne',
    sourceId: '411',
    externalId: 'the-batman-2022-bruce-wayne',
    title: 'The Batman (2022) - Bruce Wayne & Batman',
    mediaTitle: 'The Batman',
    mediaType: 'movie',
    year: 2022,
    characterName: 'Bruce Wayne',
    actorName: 'Robert Pattinson',
    directorName: 'Matt Reeves',
    creatorName: 'AeroEdits',
    category: 'Movie Scenepacks',
    quality: '1080p',
    codec: 'H.264',
    description: 'Quiet lonely night scenes, screaming in the rain, flare in floodwater, funeral confrontation, revenge monologue, dark aesthetic walking.',
    sourceUrl: 'https://scenepacks.com/pack/the-batman-2022-bruce-wayne',
    downloadPageUrl: 'https://scenepacks.com/download/the-batman-2022',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg',
    popularity: 99,
    downloadCount: 8900,
    publishedAt: '2023-01-20T10:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['the batman', 'bruce wayne', 'robert pattinson', 'rain', 'screaming in the rain', 'night', 'lonely', 'revenge', 'funeral'],
    vibeTags: ['rain', 'night', 'loneliness', 'anger', 'revenge', 'grief', 'badass', 'sad edit'],
  },
  {
    id: 'suits_the_batman_4k',
    sourceId: 'suits',
    externalId: 'the-batman-suits-4k',
    title: 'The Batman (2022) - Full Film Pack [4K Pro]',
    mediaTitle: 'The Batman',
    mediaType: 'movie',
    year: 2022,
    characterName: 'Bruce Wayne',
    actorName: 'Robert Pattinson',
    directorName: 'Matt Reeves',
    creatorName: 'SuitsTM',
    category: '4K Cinema',
    quality: '4K',
    codec: 'H.265 (HEVC)',
    description: 'Complete 4K raw clips, car chase in rain with Penguin, flare leading survivors, batmobile fire engine roar, highway explosion.',
    sourceUrl: 'https://suitstmscenepacks.com/pack/the-batman-4k',
    downloadPageUrl: 'https://suitstmscenepacks.com/download/the-batman-4k',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/74xTEgt7R36Fpooo50r9T25onhq.jpg',
    popularity: 94,
    downloadCount: 6420,
    publishedAt: '2023-04-12T16:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['the batman', '4k', 'batmobile', 'car chase', 'rain', 'fight', 'action', 'velocity'],
    vibeTags: ['fight', 'rain', 'night', 'badass', 'velocity', 'anger'],
  },

  // EUPHORIA (TV Series)
  {
    id: 'veel_euphoria_rue_bennett',
    sourceId: 'veel',
    externalId: 'euphoria-rue-bennett-s1-s2',
    title: 'Euphoria (Season 1 & 2) - Rue Bennett',
    mediaTitle: 'Euphoria',
    mediaType: 'tv',
    year: 2019,
    characterName: 'Rue Bennett',
    actorName: 'Zendaya',
    directorName: 'Sam Levinson',
    creatorName: 'Veel SCP',
    category: 'TV Series',
    quality: '1080p',
    codec: 'H.264',
    description: 'Girl crying alone in bedroom, panic attack, screaming argument with mother Leslie, sad breakup with Jules, glitter tears, emotional breakdown.',
    sourceUrl: 'https://veelscp.com/pack/euphoria-rue-bennett',
    downloadPageUrl: 'https://veelscp.com/dl/euphoria-rue',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/mez2Z3WqlPKNXpi7mWoiiE5guE9.jpg',
    popularity: 100,
    downloadCount: 12500,
    publishedAt: '2023-01-05T18:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['euphoria', 'rue bennett', 'zendaya', 'crying alone', 'panic attack', 'mother and daughter arguing', 'breakup', 'grief', 'sad edit'],
    vibeTags: ['sadness', 'grief', 'heartbreak', 'panic attack', 'argument', 'crying', 'sad edit', 'loneliness'],
  },
  {
    id: '411_euphoria_jules_maddy',
    sourceId: '411',
    externalId: 'euphoria-girls-pack',
    title: 'Euphoria - Maddy & Cassie Conflict Pack',
    mediaTitle: 'Euphoria',
    mediaType: 'tv',
    year: 2019,
    characterName: 'Maddy Perez',
    actorName: 'Alexa Demie',
    directorName: 'Sam Levinson',
    creatorName: '411 Crew',
    category: 'TV Series',
    quality: '1080p',
    codec: 'H.264',
    description: 'Someone realizes their best friend betrayed them, bathroom confrontation, luxury party looks, badass hallway walk, screaming betrayal.',
    sourceUrl: 'https://scenepacks.com/pack/euphoria-maddy-cassie',
    downloadPageUrl: 'https://scenepacks.com/download/euphoria-maddy-cassie',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/oKt4J3TFjWirVwBqoHyIvv5IImd.jpg',
    popularity: 91,
    downloadCount: 4700,
    publishedAt: '2023-02-18T11:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['euphoria', 'maddy perez', 'cassie', 'betrayal', 'friend betrayed', 'party', 'argument', 'badass entrance'],
    vibeTags: ['betrayal', 'argument', 'badass', 'party', 'confidence', 'heartbreak'],
  },

  // SPIDER-MAN
  {
    id: 'veel_spiderman_peter_parker',
    sourceId: 'veel',
    externalId: 'spiderman-peter-parker-trilogy',
    title: 'Spider-Man - Peter Parker Emotional & Loss Pack',
    mediaTitle: 'Spider-Man',
    mediaType: 'movie',
    year: 2021,
    characterName: 'Peter Parker',
    actorName: 'Tom Holland / Andrew Garfield',
    directorName: 'Jon Watts',
    creatorName: 'Veel SCP',
    category: 'Movie Scenepacks',
    quality: '1080p',
    codec: 'H.264',
    description: 'Losing someone you love, guy screaming in rain, holding dying Aunt May and Gwen Stacy, crying in rain on rooftop, heroic grief.',
    sourceUrl: 'https://veelscp.com/pack/spiderman-emotional-loss',
    downloadPageUrl: 'https://veelscp.com/dl/spiderman-grief',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg',
    popularity: 97,
    downloadCount: 9800,
    publishedAt: '2023-01-12T08:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['spider-man', 'spiderman', 'peter parker', 'grief', 'crying in the rain', 'loss of loved one', 'screaming', 'sad edit'],
    vibeTags: ['grief', 'sadness', 'rain', 'crying', 'anger', 'sad edit', 'fight'],
  },

  // SUCCESSION
  {
    id: 'suits_succession_kendall_roy',
    sourceId: 'suits',
    externalId: 'succession-kendall-roy-tragedy',
    title: 'Succession - Kendall Roy Breakdown & Betrayal',
    mediaTitle: 'Succession',
    mediaType: 'tv',
    year: 2018,
    characterName: 'Kendall Roy',
    actorName: 'Jeremy Strong',
    directorName: 'Mark Mylod',
    creatorName: 'SuitsTM',
    category: 'TV Scenepacks',
    quality: '1080p',
    codec: 'H.264',
    description: 'Character sitting alone after losing everything, realizing they were betrayed by family, crying in kitchen, listening to sad song in car, rooftop melancholy.',
    sourceUrl: 'https://suitstmscenepacks.com/pack/succession-kendall-roy',
    downloadPageUrl: 'https://suitstmscenepacks.com/download/succession-kendall',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/bcdUYUFk8GdpZJPiSAas9UeocLH.jpg',
    popularity: 92,
    downloadCount: 5200,
    publishedAt: '2023-03-25T13:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['succession', 'kendall roy', 'betrayal', 'breakdown', 'sitting alone after losing everything', 'sad edit', 'luxury', 'lonely'],
    vibeTags: ['betrayal', 'loneliness', 'sadness', 'heartbreak', 'sad edit', 'argument'],
  },

  // INTERSTELLAR (2014)
  {
    id: '411_interstellar_cooper',
    sourceId: '411',
    externalId: 'interstellar-2014-cooper-murph',
    title: 'Interstellar (2014) - Cooper & Murph Farewell & Messages',
    mediaTitle: 'Interstellar',
    mediaType: 'movie',
    year: 2014,
    characterName: 'Joseph Cooper',
    actorName: 'Matthew McConaughey',
    directorName: 'Christopher Nolan',
    creatorName: 'CinemaEdit411',
    category: 'Sci-Fi Masterpieces',
    quality: '1080p',
    codec: 'H.264',
    description: 'Crying watching 23 years of video messages, emotional goodbye in truck, father daughter reunion in hospital bed, clips for a sad edit.',
    sourceUrl: 'https://scenepacks.com/pack/interstellar-cooper-murph',
    downloadPageUrl: 'https://scenepacks.com/download/interstellar-2014',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    popularity: 98,
    downloadCount: 11200,
    publishedAt: '2023-01-08T19:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['interstellar', 'intersteller', 'cooper', 'murph', 'crying watching video messages', 'goodbye', 'reunion', 'emotional', 'sad edit'],
    vibeTags: ['grief', 'sadness', 'crying', 'reunion', 'sad edit', 'loneliness'],
  },

  // ARCANE
  {
    id: 'editpacks_arcane_jinx_vi',
    sourceId: 'editpacks',
    externalId: 'arcane-jinx-vi-tragedy',
    title: 'Arcane - Jinx & Vi Broken Bond Pack',
    mediaTitle: 'Arcane',
    mediaType: 'anime',
    year: 2021,
    characterName: 'Jinx / Powder',
    actorName: 'Ella Purnell',
    directorName: 'Pascal Charrue',
    creatorName: 'EditPacks Animation',
    category: 'Animated Scenepacks',
    quality: '1080p',
    codec: 'H.264',
    description: 'Girl crying after losing family, panic attack with flare, villain smiling through tears, tea party betrayal reveal, neon chaotic fight.',
    sourceUrl: 'https://editpacks.org/pack/arcane-jinx-vi',
    downloadPageUrl: 'https://editpacks.org/dl/arcane-jinx',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/q8eejQcg1bAqImEV8jh8RtBD4uH.jpg',
    popularity: 97,
    downloadCount: 8100,
    publishedAt: '2023-02-14T20:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['arcane', 'jinx', 'vi', 'powder', 'panic attack', 'crying alone', 'betrayal', 'villain', 'reunion', 'sad edit'],
    vibeTags: ['panic attack', 'sadness', 'betrayal', 'villain', 'crying', 'fight', 'sad edit'],
  },

  // PEAKY BLINDERS
  {
    id: 'suits_peaky_blinders_thomas_shelby',
    sourceId: 'suits',
    externalId: 'peaky-blinders-thomas-shelby-aura',
    title: 'Peaky Blinders - Thomas Shelby Badass & Revenge',
    mediaTitle: 'Peaky Blinders',
    mediaType: 'tv',
    year: 2013,
    characterName: 'Thomas Shelby',
    actorName: 'Cillian Murphy',
    directorName: 'Steven Knight',
    creatorName: 'SuitsTM',
    category: 'TV Series',
    quality: '1080p',
    codec: 'H.264',
    description: 'Confident entrance scene, slow motion walking with cigarette, cold revenge moments, badass aura clips for phonk and velocity edits.',
    sourceUrl: 'https://suitstmscenepacks.com/pack/peaky-blinders-thomas-shelby',
    downloadPageUrl: 'https://suitstmscenepacks.com/download/peaky-blinders-tommy',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/3UupR0nS9R6Di9letdz4ftX95GF.jpg',
    popularity: 95,
    downloadCount: 7800,
    publishedAt: '2023-01-28T14:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['peaky blinders', 'thomas shelby', 'cillian murphy', 'badass walking', 'confident entrance', 'revenge', 'velocity', 'hype'],
    vibeTags: ['badass', 'confidence', 'revenge', 'velocity', 'night'],
  },

  // BREAKING BAD
  {
    id: '411_breaking_bad_walter_white',
    sourceId: '411',
    externalId: 'breaking-bad-walter-white-despair',
    title: 'Breaking Bad - Walter White Crawl Space & Despair',
    mediaTitle: 'Breaking Bad',
    mediaType: 'tv',
    year: 2008,
    characterName: 'Walter White',
    actorName: 'Bryan Cranston',
    directorName: 'Vince Gilligan',
    creatorName: '411 Classic',
    category: 'TV Series',
    quality: '1080p',
    codec: 'H.264',
    description: 'Hysterical laughing in despair in crawl space, realizing they made a huge mistake, losing everything, desert screaming confrontation.',
    sourceUrl: 'https://scenepacks.com/pack/breaking-bad-walter-white',
    downloadPageUrl: 'https://scenepacks.com/download/breaking-bad-walter',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg',
    popularity: 96,
    downloadCount: 6900,
    publishedAt: '2023-02-05T10:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['breaking bad', 'walter white', 'bryan cranston', 'crawl space', 'laughing in despair', 'losing everything', 'villain', 'shock'],
    vibeTags: ['villain', 'sadness', 'panic attack', 'shock', 'betrayal'],
  },

  // THE LAST OF US
  {
    id: 'veel_the_last_of_us_joel_ellie',
    sourceId: 'veel',
    externalId: 'the-last-of-us-joel-ellie',
    title: 'The Last of Us (2023) - Joel Miller & Ellie Williams',
    mediaTitle: 'The Last of Us',
    mediaType: 'tv',
    year: 2023,
    characterName: 'Joel Miller',
    actorName: 'Pedro Pascal',
    directorName: 'Craig Mazin',
    creatorName: 'Veel SCP',
    category: 'TV Series',
    quality: '4K',
    codec: 'H.265 (HEVC)',
    description: 'Father crying holding dying daughter Sarah, quiet emotional bond in snow, hospital rescue rage, grief and protective violence.',
    sourceUrl: 'https://veelscp.com/pack/the-last-of-us-joel-ellie',
    downloadPageUrl: 'https://veelscp.com/dl/last-of-us-4k',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg',
    popularity: 97,
    downloadCount: 8400,
    publishedAt: '2023-03-15T15:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['the last of us', 'last of us', 'joel miller', 'pedro pascal', 'ellie', 'father crying', 'grief', 'daughter death', '4k'],
    vibeTags: ['grief', 'sadness', 'crying', 'fight', 'anger', 'sad edit'],
  },

  // OPPENHEIMER (2023)
  {
    id: 'editpacks_oppenheimer_4k',
    sourceId: 'editpacks',
    externalId: 'oppenheimer-2023-4k',
    title: 'Oppenheimer (2023) - J. Robert Oppenheimer [4K]',
    mediaTitle: 'Oppenheimer',
    mediaType: 'movie',
    year: 2023,
    characterName: 'J. Robert Oppenheimer',
    actorName: 'Cillian Murphy',
    directorName: 'Christopher Nolan',
    creatorName: 'EditPacks Master',
    category: '4K Cinema',
    quality: '4K',
    codec: 'H.265 (HEVC)',
    description: 'Panic attack in gymnasium applause scene, quiet loneliness by pond with Einstein, guilt and regret, blinding white explosion silence.',
    sourceUrl: 'https://editpacks.org/pack/oppenheimer-2023-4k',
    downloadPageUrl: 'https://editpacks.org/dl/oppenheimer-4k',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg',
    popularity: 95,
    downloadCount: 6700,
    publishedAt: '2023-08-01T12:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['oppenheimer', 'openheimer', 'cillian murphy', 'panic attack', 'guilt', 'regret', 'silence', '4k'],
    vibeTags: ['panic attack', 'loneliness', 'sadness', 'shock'],
  },

  // LA LA LAND (Romance / Heartbreak)
  {
    id: '411_la_la_land_ending',
    sourceId: '411',
    externalId: 'la-la-land-ending-nod',
    title: 'La La Land (2016) - Mia & Sebastian Epilogue & Look',
    mediaTitle: 'La La Land',
    mediaType: 'movie',
    year: 2016,
    characterName: 'Mia Dolan & Sebastian Wilder',
    actorName: 'Emma Stone / Ryan Gosling',
    directorName: 'Damien Chazelle',
    creatorName: '411 Romance',
    category: 'Romance Scenepacks',
    quality: '1080p',
    codec: 'H.264',
    description: 'Couple looking at each other without talking, romantic eye contact, final bittersweet smile, nostalgic flashback of what could have been.',
    sourceUrl: 'https://scenepacks.com/pack/la-la-land-epilogue',
    downloadPageUrl: 'https://scenepacks.com/download/la-la-land',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/nlPCdZlHtRNcF6C9hzUH4ebmV1w.jpg',
    popularity: 93,
    downloadCount: 5600,
    publishedAt: '2023-02-12T17:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['la la land', 'ryan gosling', 'emma stone', 'romantic eye contact', 'looking at each other without talking', 'bittersweet smile', 'heartbreak', 'nostalgia'],
    vibeTags: ['romance', 'heartbreak', 'nostalgia', 'sadness', 'sad edit'],
  },

  // STRANGER THINGS
  {
    id: 'veel_stranger_things_eleven_max',
    sourceId: 'veel',
    externalId: 'stranger-things-s4-emotional',
    title: 'Stranger Things 4 - Max & Eleven Emotional Moments',
    mediaTitle: 'Stranger Things',
    mediaType: 'tv',
    year: 2016,
    characterName: 'Eleven & Max Mayfield',
    actorName: 'Millie Bobby Brown / Sadie Sink',
    directorName: 'The Duffer Brothers',
    creatorName: 'Veel SCP',
    category: 'TV Series',
    quality: '1080p',
    codec: 'H.264',
    description: 'Dear Billy cemetery scene, running up that hill, girl crying after losing someone, scary red mindscape, friendship goodbye.',
    sourceUrl: 'https://veelscp.com/pack/stranger-things-max-eleven',
    downloadPageUrl: 'https://veelscp.com/dl/stranger-things-s4',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
    popularity: 96,
    downloadCount: 7600,
    publishedAt: '2023-01-22T21:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['stranger things', 'strangerthings', 'eleven', 'max mayfield', 'grief', 'sad edit', 'crying', 'friendship', 'running up that hill'],
    vibeTags: ['grief', 'sadness', 'crying', 'friendship', 'fight', 'sad edit'],
  },

  // FIGHT CLUB (1999)
  {
    id: 'suits_fight_club_tyler_durden',
    sourceId: 'suits',
    externalId: 'fight-club-tyler-durden-4k',
    title: 'Fight Club (1999) - Tyler Durden & The Narrator [4K]',
    mediaTitle: 'Fight Club',
    mediaType: 'movie',
    year: 1999,
    characterName: 'Tyler Durden / The Narrator',
    actorName: 'Brad Pitt / Edward Norton',
    directorName: 'David Fincher',
    creatorName: 'SuitsTM',
    category: '4K Cinema',
    quality: '4K',
    codec: 'H.265 (HEVC)',
    description: 'Badass sigma clips, realizing they are the same person, bloody smile in basement, building collapse holding hands ending, monologue about consumerism.',
    sourceUrl: 'https://suitstmscenepacks.com/pack/fight-club-4k',
    downloadPageUrl: 'https://suitstmscenepacks.com/download/fight-club-4k',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/hZkgoQYus5vegHoetLkCJzb17zJ.jpg',
    popularity: 97,
    downloadCount: 8900,
    publishedAt: '2023-05-10T14:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['fight club', 'tyler durden', 'brad pitt', 'edward norton', 'badass', 'sigma', 'fight', 'blood', 'mind blown', 'velocity'],
    vibeTags: ['fight', 'badass', 'confidence', 'blood', 'velocity', 'shock'],
  },

  // DUNE: PART TWO (2024)
  {
    id: 'veel_dune_part_two_paul_atreides',
    sourceId: 'veel',
    externalId: 'dune-part-two-paul-atreides-4k',
    title: 'Dune: Part Two (2024) - Paul Atreides & Feyd-Rautha [4K HDR]',
    mediaTitle: 'Dune: Part Two',
    mediaType: 'movie',
    year: 2024,
    characterName: 'Paul Atreides',
    actorName: 'Timothée Chalamet / Austin Butler',
    directorName: 'Denis Villeneuve',
    creatorName: 'Veel SCP Master',
    category: '4K Cinema',
    quality: '4K',
    codec: 'H.265 (HEVC)',
    description: 'Silence speech in war council, riding the sandworm, knife duel with Feyd-Rautha, lead them to paradise speech, holy war begins.',
    sourceUrl: 'https://veelscp.com/pack/dune-2-4k',
    downloadPageUrl: 'https://veelscp.com/dl/dune-2-4k',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    popularity: 99,
    downloadCount: 14200,
    publishedAt: '2024-03-20T18:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['dune', 'dune 2', 'paul atreides', 'timothee chalamet', 'feyd-rautha', 'austin butler', 'sandworm', 'badass entrance', 'power', '4k'],
    vibeTags: ['badass', 'confidence', 'fight', 'anger', 'velocity'],
  },

  // THE BOYS (2019)
  {
    id: '411_the_boys_homelander_butcher',
    sourceId: '411',
    externalId: 'the-boys-homelander-butcher',
    title: 'The Boys - Homelander & Billy Butcher Unhinged Pack',
    mediaTitle: 'The Boys',
    mediaType: 'tv',
    year: 2019,
    characterName: 'Homelander & Billy Butcher',
    actorName: 'Antony Starr / Karl Urban',
    directorName: 'Eric Kripke',
    creatorName: '411 Archive',
    category: 'TV Series',
    quality: '1080p',
    codec: 'H.264',
    description: 'Unhinged laser eyes, villain smiling creepily in mirror, covered in blood laughing, violent revenge, screaming oi cunt.',
    sourceUrl: 'https://scenepacks.com/pack/the-boys-homelander-butcher',
    downloadPageUrl: 'https://scenepacks.com/download/the-boys',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg',
    popularity: 98,
    downloadCount: 11800,
    publishedAt: '2023-06-15T16:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['the boys', 'homelander', 'billy butcher', 'antony starr', 'unhinged', 'laser eyes', 'villain', 'covered in blood', 'revenge'],
    vibeTags: ['villain', 'blood', 'badass', 'anger', 'fight', 'shock'],
  },

  // BLADE RUNNER 2049 (2017)
  {
    id: 'editpacks_blade_runner_2049_officer_k',
    sourceId: 'editpacks',
    externalId: 'blade-runner-2049-officer-k',
    title: 'Blade Runner 2049 (2017) - Officer K / Joe [4K]',
    mediaTitle: 'Blade Runner 2049',
    mediaType: 'movie',
    year: 2017,
    characterName: 'Officer K / Joe',
    actorName: 'Ryan Gosling',
    directorName: 'Denis Villeneuve',
    creatorName: 'EditPacks Master',
    category: '4K Cinema',
    quality: '4K',
    codec: 'H.265 (HEVC)',
    description: 'You look lonely giant holographic Joi scene, screaming baseline test, lying on steps in snow ending, quiet melancholic walking.',
    sourceUrl: 'https://editpacks.org/pack/blade-runner-2049-officer-k',
    downloadPageUrl: 'https://editpacks.org/dl/blade-runner-4k',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
    popularity: 96,
    downloadCount: 9300,
    publishedAt: '2023-04-18T19:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['blade runner 2049', 'blade runner', 'officer k', 'ryan gosling', 'you look lonely', 'joi', 'lonely', 'sad edit', 'snow ending'],
    vibeTags: ['loneliness', 'sadness', 'nostalgia', 'sad edit', 'night'],
  },

  // WHIPLASH (2014)
  {
    id: 'suits_whiplash_andrew_neiman',
    sourceId: 'suits',
    externalId: 'whiplash-andrew-neiman-fletcher',
    title: 'Whiplash (2014) - Andrew Neiman & Fletcher Final Solo',
    mediaTitle: 'Whiplash',
    mediaType: 'movie',
    year: 2014,
    characterName: 'Andrew Neiman & Terence Fletcher',
    actorName: 'Miles Teller / J.K. Simmons',
    directorName: 'Damien Chazelle',
    creatorName: 'SuitsTM',
    category: 'Movie Scenepacks',
    quality: '1080p',
    codec: 'H.264',
    description: 'Blood on drum cymbals, intense bleeding fingers, caravan final solo smiling nod at Fletcher, obsessively practicing until exhaustion.',
    sourceUrl: 'https://suitstmscenepacks.com/pack/whiplash-final-solo',
    downloadPageUrl: 'https://suitstmscenepacks.com/download/whiplash',
    thumbnailUrl: 'https://image.tmdb.org/t/p/w780/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg',
    popularity: 95,
    downloadCount: 7400,
    publishedAt: '2023-07-11T13:00:00Z',
    indexedAt: new Date().toISOString(),
    lastCheckedAt: new Date().toISOString(),
    isActive: true,
    tags: ['whiplash', 'andrew neiman', 'miles teller', 'fletcher', 'jk simmons', 'drum solo', 'blood', 'obsession', 'badass', 'velocity'],
    vibeTags: ['blood', 'badass', 'anger', 'confidence', 'velocity'],
  }
];

// Initialize packs with local pre-computed embedding vectors
export const MOCK_PACKS: Pack[] = RAW_PACKS_DATA.map(pack => {
  const embeddingText = [
    pack.title,
    pack.mediaTitle,
    pack.characterName || '',
    pack.actorName || '',
    pack.description || '',
    ...(pack.tags || []),
    ...(pack.vibeTags || [])
  ].join(' ');
  return {
    ...pack,
    embedding: generateLocalEmbedding(embeddingText),
  };
});

export function getMockDiagnostics(): DiagnosticsData {
  const packsPerSource: Record<string, number> = {
    '411': MOCK_PACKS.filter(p => p.sourceId === '411').length,
    'veel': MOCK_PACKS.filter(p => p.sourceId === 'veel').length,
    'editpacks': MOCK_PACKS.filter(p => p.sourceId === 'editpacks').length,
    'suits': MOCK_PACKS.filter(p => p.sourceId === 'suits').length,
  };

  return {
    totalIndexedPacks: MOCK_PACKS.length * 280, // Scaled for display representation
    packsPerSource: packsPerSource as any,
    lastCrawlTimes: {
      '411': new Date(Date.now() - 3600000 * 4).toISOString(),
      'veel': new Date(Date.now() - 3600000 * 2).toISOString(),
      'editpacks': new Date(Date.now() - 3600000 * 7).toISOString(),
      'suits': new Date(Date.now() - 3600000 * 5).toISOString(),
    },
    activeSources: INITIAL_SOURCES,
    inactiveLinksCount: 0,
    duplicateGroupCount: 6,
    averageSearchLatencyMs: 18,
    failedCrawlPages: [],
    tagCount: 142,
    isLiveIndex: false,
  };
}
